# Generated by Django 4.2.6 on 2025-04-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='data_horario_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
