# Generated by Django 4.2.6 on 2023-12-05 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=120, unique=True)),
                ('valor_procedimento', models.DecimalField(decimal_places=2, max_digits=8)),
                ('faces', models.IntegerField(default=3, max_length=1)),
                ('outros', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orcamentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('procedimento', models.ManyToManyField(to='OrcamentoPaciente.procedimento')),
            ],
        ),
    ]
