# Generated by Django 4.2.6 on 2023-12-05 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroUsuario', '0015_alter_cadastropacientes_cpf'),
        ('OrcamentoPaciente', '0002_alter_procedimento_faces'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamentacao',
            name='paciente',
            field=models.ManyToManyField(to='CadastroUsuario.cadastropacientes'),
        ),
    ]
