# Generated by Django 4.2.6 on 2023-12-06 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrcamentoPaciente', '0003_orcamentacao_paciente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orcamentacao',
        ),
    ]
