# Generated by Django 4.2.6 on 2023-12-07 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroUsuario', '0015_alter_cadastropacientes_cpf'),
        ('OrcamentoPaciente', '0004_delete_orcamentacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CadastroUsuario.cadastropacientes')),
                ('procedimentos', models.ManyToManyField(to='OrcamentoPaciente.procedimento')),
            ],
        ),
    ]
