# Generated by Django 4.2.6 on 2023-12-07 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrcamentoPaciente', '0005_orcamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orcamento',
            old_name='paciente',
            new_name='nome',
        ),
    ]
