# Generated by Django 4.2.6 on 2023-12-07 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrcamentoPaciente', '0006_rename_paciente_orcamento_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orcamento',
            old_name='nome',
            new_name='paciente',
        ),
    ]
