# Generated by Django 4.2.6 on 2023-12-09 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrcamentoPaciente', '0007_rename_nome_orcamento_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='procedimentos',
        ),
        migrations.CreateModel(
            name='Dentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_dente', models.CharField(max_length=120, unique=True)),
                ('imagem_dente', models.ImageField(default=None, upload_to='imagens-dentes/')),
                ('procedimentos', models.ManyToManyField(to='OrcamentoPaciente.procedimento')),
            ],
        ),
    ]
