# Generated by Django 4.2.6 on 2023-12-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrcamentoPaciente', '0009_alter_dentes_imagem_dente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dentes',
            name='procedimentos',
        ),
        migrations.AddField(
            model_name='orcamento',
            name='calcular_total',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='procedimentos',
            field=models.ManyToManyField(to='OrcamentoPaciente.procedimento'),
        ),
    ]
