# Generated by Django 4.2.6 on 2023-12-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrcamentoPaciente', '0010_remove_dentes_procedimentos_orcamento_calcular_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='dentes',
            field=models.ManyToManyField(to='OrcamentoPaciente.dentes'),
        ),
    ]
