# Generated by Django 4.2.6 on 2023-12-10 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrcamentoPaciente', '0011_orcamento_dentes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='dentes',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='procedimentos',
        ),
        migrations.CreateModel(
            name='OrcamentoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrcamentoPaciente.dentes')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrcamentoPaciente.orcamento')),
                ('procedimentos', models.ManyToManyField(to='OrcamentoPaciente.procedimento')),
            ],
        ),
    ]
