# Generated by Django 4.2.6 on 2023-12-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrcamentoPaciente', '0012_remove_orcamento_data_criacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentes',
            name='nome_dente',
            field=models.CharField(max_length=120),
        ),
    ]
