# Generated by Django 4.2.6 on 2023-12-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrcamentoPaciente', '0013_alter_dentes_nome_dente'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentes',
            name='procedimentos',
            field=models.ManyToManyField(to='OrcamentoPaciente.procedimento'),
        ),
    ]
