# Generated by Django 4.2.6 on 2023-12-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrcamentoPaciente', '0014_dentes_procedimentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriarOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(max_length=120, unique=True)),
                ('dente', models.CharField(max_length=120, unique=True)),
                ('procedimento', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='dentes',
            name='procedimentos',
        ),
        migrations.AlterField(
            model_name='dentes',
            name='nome_dente',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
