# Generated by Django 4.2.6 on 2023-12-19 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrcamentoPaciente', '0015_criarorcamento_remove_dentes_procedimentos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criarorcamento',
            name='procedimento',
            field=models.CharField(max_length=120),
        ),
    ]
