# Generated by Django 4.2.6 on 2023-12-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrcamentoPaciente', '0017_alter_criarorcamento_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criarorcamento',
            name='dente',
            field=models.CharField(max_length=120),
        ),
    ]
