# Generated by Django 4.2.6 on 2023-12-22 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrcamentoPaciente', '0020_alter_criarorcamento_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criarorcamento',
            name='usuario',
        ),
    ]
