# Generated by Django 4.2.6 on 2023-12-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrcamentoPaciente', '0022_alter_criarorcamento_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criarorcamento',
            name='paciente',
            field=models.CharField(max_length=120),
        ),
    ]
