# Generated by Django 4.2.6 on 2023-12-23 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrcamentoPaciente', '0026_remove_criarorcamento_procedimento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criarorcamento',
            old_name='procedimento',
            new_name='procedimentos',
        ),
    ]
