# Generated by Django 4.2.6 on 2023-12-29 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroUsuario', '0018_alter_cadastropacientes_usuario'),
        ('OrcamentoPaciente', '0028_rename_procedimentos_criarorcamento_procedimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='TB_Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orcamento', models.PositiveIntegerField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('calcular_total', models.BooleanField(default=False)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CadastroUsuario.cadastropacientes')),
            ],
        ),
    ]
