# Generated by Django 4.2.6 on 2023-12-30 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrcamentoPaciente', '0029_tb_orcamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='criarorcamento',
            name='numero_orcamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='OrcamentoPaciente.tb_orcamento'),
        ),
    ]
