# Generated by Django 4.2.6 on 2023-12-31 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CadastroUsuario', '0018_alter_cadastropacientes_usuario'),
        ('OrcamentoPaciente', '0031_orcamentoitem_numero_orcamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criarorcamento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_orcamento', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tb_orcamento',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos_historicos', to='CadastroUsuario.cadastropacientes'),
        ),
    ]
