# Generated by Django 4.2.6 on 2023-12-31 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('OrcamentoPaciente', '0032_alter_criarorcamento_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criarorcamento',
            name='numero_orcamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamento_criado', to='OrcamentoPaciente.tb_orcamento'),
        ),
        migrations.AlterField(
            model_name='criarorcamento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orcamentoitem',
            name='numero_orcamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_orcamento', to='OrcamentoPaciente.tb_orcamento'),
        ),
    ]
