# Generated by Django 4.2.6 on 2024-01-22 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrcamentoPaciente', '0034_rename_numero_orcamento_criarorcamento_numero_orcamento1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criarorcamento',
            name='procedimento',
            field=models.ManyToManyField(related_name='escolher_procedimento', to='OrcamentoPaciente.procedimento'),
        ),
    ]
