# Generated by Django 4.2.6 on 2024-01-22 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrcamentoPaciente', '0035_alter_criarorcamento_procedimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='criarorcamento',
            name='custo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
