# Generated by Django 4.2.6 on 2024-10-15 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroPacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('cpf', models.CharField(max_length=20, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=40)),
                ('data_nascimento', models.DateField()),
                ('profissao', models.CharField(max_length=40)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('cidade', models.CharField(blank=True, max_length=20, null=True)),
                ('bairro', models.CharField(blank=True, max_length=20, null=True)),
                ('rua', models.CharField(blank=True, max_length=20, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('complemento', models.TextField(blank=True, max_length=400, null=True)),
                ('alergia', models.CharField(max_length=400)),
                ('doencas_conhecidas', models.CharField(max_length=400)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('imagem', models.ImageField(default=None, upload_to='images/')),
                ('nome', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CadastroUsuario.cadastropacientes')),
            ],
        ),
    ]
