# Generated by Django 4.2.6 on 2023-10-18 22:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroUsuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastropacientes',
            name='data_nascimento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
