# Generated by Django 4.2.6 on 2023-11-18 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroUsuario', '0002_cadastropacientes_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastropacientes',
            name='imagem',
            field=models.ImageField(default=0, upload_to='imagens/'),
            preserve_default=False,
        ),
    ]
