# Generated by Django 4.2.6 on 2023-11-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroUsuario', '0002_cadastropacientes_data_nascimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('img', models.ImageField(default=None, upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='cadastropacientes',
            name='data_nascimento',
            field=models.DateField(),
        ),
    ]
