# Generated by Django 4.2.6 on 2023-11-18 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroUsuario', '0003_cadastropacientes_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastropacientes',
            name='imagem',
        ),
    ]
