# Generated by Django 4.2.6 on 2023-11-19 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroUsuario', '0003_image_alter_cadastropacientes_data_nascimento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
