# Generated by Django 4.2.6 on 2023-11-26 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroUsuario', '0009_imagea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagea',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
