# Generated by Django 4.2.6 on 2023-12-02 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroUsuario', '0010_alter_imagea_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastropacientes',
            name='cpf',
            field=models.CharField(default=0, max_length=11, unique=True),
        ),
    ]
