# Generated by Django 4.2.6 on 2023-12-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroUsuario', '0011_cadastropacientes_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastropacientes',
            name='cpf',
            field=models.CharField(default=0, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='cadastropacientes',
            name='nome',
            field=models.CharField(max_length=120),
        ),
    ]
