# Generated by Django 4.2.6 on 2023-12-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroUsuario', '0012_alter_cadastropacientes_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastropacientes',
            name='cpf',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
