# Generated by Django 4.2.6 on 2023-12-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroUsuario', '0013_alter_cadastropacientes_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastropacientes',
            name='cpf',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cadastropacientes',
            name='nome',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
