# Generated by Django 4.2.6 on 2023-12-10 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroUsuario', '0015_alter_cadastropacientes_cpf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
