# Generated by Django 4.2.6 on 2023-12-21 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CadastroUsuario', '0016_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastropacientes',
            name='usuario',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
