# Generated by Django 4.2.6 on 2024-10-15 21:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CadastroUsuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('descricao', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='Odontograma/')),
            ],
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CadastroUsuario.cadastropacientes')),
            ],
        ),
        migrations.CreateModel(
            name='ItemOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orcamentos.dente')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orcamentos.orcamento')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orcamentos.procedimento')),
            ],
        ),
    ]
