# Generated by Django 4.2.6 on 2024-06-13 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroUsuario', '0018_alter_cadastropacientes_usuario'),
        ('Orcamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos', to='CadastroUsuario.cadastropacientes'),
        ),
    ]
