# Generated by Django 4.2.6 on 2024-06-13 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orcamentos', '0002_alter_orcamento_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orcamentos.paciente'),
        ),
    ]
