# Generated by Django 4.2.6 on 2024-06-15 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroUsuario', '0018_alter_cadastropacientes_usuario'),
        ('Orcamentos', '0003_alter_orcamento_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CadastroUsuario.cadastropacientes'),
        ),
    ]
