# Generated by Django 4.2.6 on 2024-06-15 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orcamentos', '0004_alter_orcamento_paciente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paciente',
        ),
        migrations.AlterField(
            model_name='dente',
            name='imagem',
            field=models.ImageField(upload_to='Odontograma/'),
        ),
        migrations.AlterField(
            model_name='dente',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
